export const CITIES = {
	Kyiv: {
		city: 'Kyiv',
		readableName: 'Kyiv',
		requestKey: 'Kyiv, Ukraine',
		imagePath: 'assets/pictures/cities/kyiv.jpg',
	},
	Lviv: {
		city: 'Lviv',
		readableName: 'Lviv',
		requestKey: 'Lviv, Ukraine',
		imagePath: 'assets/pictures/cities/lviv.jpg',
	},
	Tokyo: {
		city: 'Tokyo',
		readableName: 'Tokyo',
		requestKey: 'Tokyo, Japan',
		imagePath: 'assets/pictures/cities/tokyo.jpg',
	},
	Delhi: {
		city: 'Delhi',
		readableName: 'Delhi',
		requestKey: 'Delhi, India',
		imagePath: 'assets/pictures/cities/delhi.jpg',
	},
	Shanghai: {
		city: 'Shanghai',
		readableName: 'Shanghai',
		requestKey: 'Shanghai, China',
		imagePath: 'assets/pictures/cities/shanghai.jpg',
	},
	Paris: {
		city: 'Paris',
		readableName: 'Paris',
		requestKey: 'Paris, France',
		imagePath: 'assets/pictures/cities/paris.jpg',
	},
	Dubai: {
		city: 'Dubai',
		readableName: 'Dubai',
		requestKey: 'Dubai, UAE',
		imagePath: 'assets/pictures/cities/dubai.jpg',
	},
	NewYorkCity: {
		city: 'NewYorkCity',
		readableName: 'New York City',
		requestKey: 'New York City, USA',
		imagePath: 'assets/pictures/cities/newyorkcity.jpg',
	},
	Istanbul: {
		city: 'Istanbul',
		readableName: 'Istanbul',
		requestKey: 'Istanbul, Turkey',
		imagePath: 'assets/pictures/cities/istanbul.jpg',
	},
	KualaLumpur: {
		city: 'KualaLumpur',
		readableName: 'Kuala Lumpur',
		requestKey: 'Kuala Lumpur, Malaysia',
		imagePath: 'assets/pictures/cities/kualalumpur.jpg',
	},
	Barcelona: {
		city: 'Barcelona',
		readableName: 'Barcelona',
		requestKey: 'Barcelona, Spain',
		imagePath: 'assets/pictures/cities/barcelona.jpg',
	},
	Amsterdam: {
		city: 'Amsterdam',
		readableName: 'Amsterdam',
		requestKey: 'Amsterdam, Netherlands',
		imagePath: 'assets/pictures/cities/amsterdam.jpg',
	},
	LosAngeles: {
		city: 'LosAngeles',
		readableName: 'Los Angeles',
		requestKey: 'Los Angeles, USA',
		imagePath: 'assets/pictures/cities/losangeles.jpg',
	},
	Rome: {
		city: 'Rome',
		readableName: 'Rome',
		requestKey: 'Rome, Italy',
		imagePath: 'assets/pictures/cities/rome.jpg',
	},
	Bangkok: {
		city: 'Bangkok',
		readableName: 'Bangkok',
		requestKey: 'Bangkok, Thailand',
		imagePath: 'assets/pictures/cities/bangkok.jpg',
	},
	London: {
		city: 'London',
		readableName: 'London',
		requestKey: 'London, UK',
		imagePath: 'assets/pictures/cities/london.jpg',
	},
	HongKong: {
		city: 'HongKong',
		readableName: 'Hong Kong',
		requestKey: 'Hong Kong, China',
		imagePath: 'assets/pictures/cities/hongkong.jpg',
	},
	Singapore: {
		city: 'Singapore',
		readableName: 'Singapore',
		requestKey: 'Singapore, Singapore',
		imagePath: 'assets/pictures/cities/singapore.jpg',
	},
	Seoul: {
		city: 'Seoul',
		readableName: 'Seoul',
		requestKey: 'Seoul, South Korea',
		imagePath: 'assets/pictures/cities/seoul.jpg',
	},
	Prague: {
		city: 'Prague',
		readableName: 'Prague',
		requestKey: 'Prague, Czech Republic',
		imagePath: 'assets/pictures/cities/prague.jpg',
	},
} as const;
